name: Deploy to Server

on:
  push:
    branches:
      - main
      - improve-model-people-recognition
      ## - dev
      ## TODO: Check best practice
      

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Deploy Code
        run: |
          cd /home/cs507/GUARDIAN
          git fetch origin ${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}
          docker compose -f docker-compose.yml up --build --force-recreate -d
